name: login and pull image ACR

on:
  push:
    branches: develop

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_GUAYOYO_URL }}
          username: ${{ secrets.ACR_GUAYOYO_USER }}
          password: ${{ secrets.ACR_GUAYOYO_TOKEN }}
      -
        name: Pull image from docker
        run: docker pull ${{ secrets.ACR_GUAYOYO_URL }}/wb-sca-dependencycheck-java 
        #docker run wb-sca-dependencycheck-java
      -
        name: Run image from docker
        run: docker run ${{ secrets.ACR_GUAYOYO_URL }}/wb-sca-dependencycheck-java:latest
        #docker run wb-sca-dependencycheck-java

#docker login -u $ACR_GUAYOYO_USER -p $ACR_GUAYOYO_TOKEN $ACR_GUAYOYO_URL

#Push image: docker push ghcr.io/OWNER/IMAGE_NAME:latest

#Pull image:
#1 copy SHA Value after Digest: docker inspect ghcr.io/OWNER/IMAGE_NAME
#2 Pull with SHA Value:  docker pull ghcr.io/OWNER/IMAGE_NAME@sha256:SHA
#Or pull by name: docker pull ghcr.io/OWNER/IMAGE_NAME
