name: Waterboa Scan Source Code
on:
  push:
    branches: develop

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ACR_GUAYOYO_URL }}
          username: ${{ secrets.ACR_GUAYOYO_USER }}
          password: ${{ secrets.ACR_GUAYOYO_TOKEN }}
          
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          architecture: x64
      
      -
        name: Pull image from docker
        run: docker pull ${{ secrets.ACR_GUAYOYO_URL }}/wb-sast-findsecbugs
      
      -
        name: Compile Project
        run:  mvn clean package -DskipTests
        #Compile project, so we can analyze project content and dependencies
        
      -
        name: Run image from docker
        run: docker run --rm -e SENDGRID_API_KEY='${{ secrets.SENDGRID_API_KEY }}' -e FROM_ADDR='${{ secrets.WB_MAIL_FROM }}'-e TO_ADDR='${{ secrets.WB_MAIL_TO }}' -e MAIL_SJT='Static Application Security Testing' -e MAIL_BODY='SAST Results' -e FILE_PATH='report.html' -e ATCH_TYPE='text/html' -e ATCH_NAME='webgoat-sast-report.html' -e ATCH_ID='002' -e ATCH_DISP='' -v '${{ github.workspace }}:/src' ${{ secrets.ACR_GUAYOYO_URL }}/wb-sast-findsecbugs:latest        

        
        #docker run --rm -e SENDGRID_API_KEY='${{ secrets.SENDGRID_API_KEY }}' -e FROM_ADDR='${{ secrets.WB_MAIL_FROM }}' -e TO_ADDR='${{ secrets.WB_MAIL_TO }}' -e MAIL_SJT='Software Composition Analysis' -e MAIL_BODY='SCA Results' -e FILE_PATH='/report/dependency-check-report.html' -e ATCH_TYPE='text/html' -e ATCH_NAME='webgoat-dependency-check-report.html' -e ATCH_ID='001' -e ATCH_DISP='' -v '${{ github.workspace }}:/src' ${{ secrets.ACR_GUAYOYO_URL }}/wb-sca-dependencycheck-java:latest        
        #docker run --rm -e SENDGRID_API_KEY='$(sendgrid_api_key)' -e FROM_ADDR='$(noreply)' -e TO_ADDR='$(email)' -e MAIL_SJT='Static Application Security Testing' -e MAIL_BODY='SAST Results' -e FILE_PATH='report.html' -e ATCH_TYPE='text/html' -e ATCH_NAME='amazona-sast-report.html' -e ATCH_ID='002' -e ATCH_DISP='' -v '$(Build.SourcesDirectory):/src' guayoyo.azurecr.io/wb-sast-findsecbugs:latest
